//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookLibrary.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.User_Books = new HashSet<User_Books>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> Genre { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Genre Genre1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Books> User_Books { get; set; }
    }
}
